version: 0.0
os: linux
files:
  - source: / 
    destination: /home/ubuntu/new_chatapp
hooks:
  ApplicationStop: 
    - location: scripts/AppStop.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/AppStart.sh
      timeout: 300
  ValidateService:
    - location: scripts/AppStatus.sh
      timeout: 300

